Repository damian-horna/scenario-quality-checker, pull requests merged in 2018-12, with the labels that each got.

#18 Sqc 15
  README.md
  pom.xml
  src/main/java/pl/poznan/put/cs/scenariochecker/controller/ScenarioController.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/ScenarioService.java
  src/main/resources/templates/home.html
  src/test/java/pl/poznan/put/cs/scenariochecker/service/ScenarioServiceTests.java
Labels: In Review, enhancement, task

#22 Sqc 21
  .gitignore
  README.md
  pom.xml
  src/main/java/pl/poznan/put/cs/scenariochecker/controller/HomeController.java
  src/main/java/pl/poznan/put/cs/scenariochecker/controller/ScenarioController.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/ScenarioService.java
  src/main/resources/static/css/bootstrap-grid.css
  src/main/resources/static/css/bootstrap-grid.css.map
  src/main/resources/static/css/bootstrap-grid.min.css
  src/main/resources/static/css/bootstrap-grid.min.css.map
  src/main/resources/static/css/bootstrap-reboot.css
  src/main/resources/static/css/bootstrap-reboot.css.map
  src/main/resources/static/css/bootstrap-reboot.min.css
  src/main/resources/static/css/bootstrap-reboot.min.css.map
  src/main/resources/static/css/bootstrap.css
  src/main/resources/static/css/bootstrap.css.map
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/bootstrap.min.css.map
  src/main/resources/static/js/bootstrap.bundle.js
  src/main/resources/static/js/bootstrap.bundle.js.map
  src/main/resources/static/js/bootstrap.bundle.min.js
  src/main/resources/static/js/bootstrap.bundle.min.js.map
  src/main/resources/static/js/bootstrap.js
  src/main/resources/static/js/bootstrap.js.map
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/bootstrap.min.js.map
  src/main/resources/static/js/exampleScenario.js
  src/main/resources/templates/home.html
  src/test/java/pl/poznan/put/cs/scenariochecker/service/ScenarioServiceTests.java
Labels: In Review, enhancement, product backlog, task

#23 Sqc 14
  src/main/java/pl/poznan/put/cs/scenariochecker/controller/ScenarioController.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/ScenarioService.java
  src/main/resources/templates/home.html
  src/test/java/pl/poznan/put/cs/scenariochecker/service/ScenarioServiceTests.java
Labels: In Review

#24 added logging
  logfile.log
  src/main/java/pl/poznan/put/cs/scenariochecker/controller/ScenarioController.java
Labels: In Review

#25 Develop
  .gitignore
  README.md
  logfile.log
  pom.xml
  src/main/java/pl/poznan/put/cs/scenariochecker/controller/HomeController.java
  src/main/java/pl/poznan/put/cs/scenariochecker/controller/ScenarioController.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/ScenarioService.java
  src/main/java/pl/poznan/put/cs/scenariochecker/transformations/CountSpecialStepsScenarioStrategy.java
  src/main/java/pl/poznan/put/cs/scenariochecker/transformations/CountStepsScenarioStrategy.java
  src/main/java/pl/poznan/put/cs/scenariochecker/transformations/CountStepsWithoutActorsNameAtTheBeginningScenarioStrategy.java
  src/main/java/pl/poznan/put/cs/scenariochecker/transformations/ScenarioHelper.java
  src/main/java/pl/poznan/put/cs/scenariochecker/transformations/ScenarioStrategy.java
  src/main/resources/static/css/bootstrap-grid.css
  src/main/resources/static/css/bootstrap-grid.css.map
  src/main/resources/static/css/bootstrap-grid.min.css
  src/main/resources/static/css/bootstrap-grid.min.css.map
  src/main/resources/static/css/bootstrap-reboot.css
  src/main/resources/static/css/bootstrap-reboot.css.map
  src/main/resources/static/css/bootstrap-reboot.min.css
  src/main/resources/static/css/bootstrap-reboot.min.css.map
  src/main/resources/static/css/bootstrap.css
  src/main/resources/static/css/bootstrap.css.map
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/bootstrap.min.css.map
  src/main/resources/static/js/bootstrap.bundle.js
  src/main/resources/static/js/bootstrap.bundle.js.map
  src/main/resources/static/js/bootstrap.bundle.min.js
  src/main/resources/static/js/bootstrap.bundle.min.js.map
  src/main/resources/static/js/bootstrap.js
  src/main/resources/static/js/bootstrap.js.map
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/bootstrap.min.js.map
  src/main/resources/static/js/exampleScenario.js
  src/main/resources/templates/home.html
  src/test/java/pl/poznan/put/cs/scenariochecker/service/ScenarioServiceTests.java
Labels: In Review

#26 add pretty printing to json in scenario service
  pom.xml
  src/main/java/pl/poznan/put/cs/scenariochecker/service/ScenarioService.java
  src/test/java/pl/poznan/put/cs/scenariochecker/service/GetSubScenariosOutputs.java
  src/test/java/pl/poznan/put/cs/scenariochecker/service/ScenarioServiceTests.java
Labels: In Review
