Repository damian-horna/scenario-quality-checker, pull requests merged in 2019-01, with the labels that each got.

#31 Endpoint with steps specified for actor
  src/main/java/pl/poznan/put/cs/scenariochecker/controller/ScenarioController.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/GetOneActorStepsService.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/RetrieveStepsWithoutActorsNameAtTheBeginningService.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/SubscenariosToDepthLevelService.java
  src/main/java/pl/poznan/put/cs/scenariochecker/transformations/CountStepsWithoutActorsNameAtTheBeginningScenarioStrategy.java
  src/main/java/pl/poznan/put/cs/scenariochecker/transformations/ScenarioHelper.java
  src/main/resources/templates/home.html
  src/test/java/pl/poznan/put/cs/scenariochecker/service/GetOneActorStepsServiceTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/service/RetrieveStepsWithoutActorsNameAtTheBeginningServiceTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/service/SubscenariosToDepthLevelServiceTest.java
Labels: In Review, enhancement

#32 goal, question, metric
  Pomiar jakości kodu.pdf
Labels: In Review

#33 Sqc 28
  src/test/java/pl/poznan/put/cs/scenariochecker/service/SubscenariosToDepthLevelServiceTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/transformations/CountSpecialStepsScenarioStrategyTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/transformations/CountStepsScenarioStrategyTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/transformations/CountStepsWithoutActorsNameAtTheBeginningTest.java
Labels: Closed

#34 Develop
  Pomiar jakości kodu.pdf
  pom.xml
  src/main/java/pl/poznan/put/cs/scenariochecker/controller/ScenarioController.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/GetOneActorStepsService.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/RetrieveStepsWithoutActorsNameAtTheBeginningService.java
  src/main/java/pl/poznan/put/cs/scenariochecker/service/SubscenariosToDepthLevelService.java
  src/main/java/pl/poznan/put/cs/scenariochecker/transformations/CountStepsWithoutActorsNameAtTheBeginningScenarioStrategy.java
  src/main/java/pl/poznan/put/cs/scenariochecker/transformations/ScenarioHelper.java
  src/main/resources/templates/home.html
  src/test/java/pl/poznan/put/cs/scenariochecker/service/GetOneActorStepsServiceTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/service/GetSubScenariosOutputs.java
  src/test/java/pl/poznan/put/cs/scenariochecker/service/RetrieveStepsWithoutActorsNameAtTheBeginningServiceTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/service/ScenarioServiceTests.java
  src/test/java/pl/poznan/put/cs/scenariochecker/service/SubscenariosToDepthLevelServiceTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/transformations/CountSpecialStepsScenarioStrategyTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/transformations/CountStepsScenarioStrategyTest.java
  src/test/java/pl/poznan/put/cs/scenariochecker/transformations/CountStepsWithoutActorsNameAtTheBeginningTest.java
Labels: In Review
